version: "3.1"
services:
  postgres:
    image:  postgres:alpine
    volumes:
      - './postgres:/postgres'
    environment:
       POSTGRES_PASSWORD: password
       POSTGRES_USER: newssite
       POSTGRES_DB: newssite-database
       PGDATA: /postgres/data
    ports:
       - 5432:5432
    

  django:
    build:
      context: ./django
      dockerfile: docker/Dockerfile
    command: ./manage.py runserver 0.0.0.0:8080
    container_name: django
    restart: always
    volumes:
      - './django:/django'
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: newssite
      DB_PASSWORD: password
      DB_NAME: newssite-database
      
